######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 19 15:54:32 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PC.h widget.h
FORMS += widget.ui
SOURCES += main.cpp PC.cpp widget.cpp
